### ISSUE TITLE
Dead link in "What's in a name? (Part two)"

### ISSUE THREAD

**Issue by JacksonChen666** [querkmachine/beeps.website#36]
In [What's in a name? (Part two) blog post](https://beeps.website/blog/2014-07-16-whats-in-a-name-part-two/), the previous post links to <https://beeps.website/2014/07/12/whats-in-a-name/> which is a 404.

**Comment by querkmachine** [comment]
Thanks for pointing this out. I've added a redirect so that the post's old URL redirects to the new one.
